spring:
  datasource:
    url: jdbc:mysql://localhost:3306/publicationdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driverclassname: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

puplication:
  firebaseUrl: https://notification-service-c8781.firebaseio.com