spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/publicationdb?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverclassname: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

puplication:
  firebaseUrl: https://notification-service-c8781.firebaseio.com